openapi: 3.0.0
info:
  title: User API
  description: API for managing users and transactions
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /users:
    get:
      summary: Get all users (Admin Only)
      tags:
        - Users
      security:
        - AdminAuth: []
      responses:
        200:
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: ObjectId
                    name:
                      type: string
                    email:
                      type: string
                    phoneNo:
                      type: string
                    role:
                      type: string

  /users/me:
    get:
      summary: Get details of the logged-in user
      tags:
        - Users
      security:
        - Auth: []
      responses:
        200:
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string

  /users/login:
    post:
      summary: User login
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful login

  /users/logout:
    post:
      summary: User logout
      tags:
        - Users
      responses:
        200:
          description: Successful logout

  /users/create:
    post:
      summary: Create a new user (Admin only)
      tags:
        - Users
      security:
        - AdminAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: User created successfully

  /users/{id}:
    get:
      summary: Get a user by ID (Admin only)
      tags:
        - Users
      security:
        - AdminAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the user to retrieve
          schema:
            type: string
      responses:
        200:
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string

components:
  securitySchemes:
    Admin:
      type: http
      scheme: bearer
      bearerFormat: JWT
    Auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
